const languages = {
  ru: {
    navbar: 'Главная',
    planets: 'Планеты',
    archive: 'архив',
    languages: 'языки',
    search: 'поиск',
    disabled: 'Недоступно',
    embrace: 'Прими свою темную силу!',
    join: 'Присоединиться к темной стороне',
    themeChange: 'тёмная/светлая',
    people: 'Люди',
    itSeems: 'Похоже по этому адресу ничего нет',
    goHome: 'Домой'
  },
  en: {
    navbar: 'Navbar',
    planets: 'Planets',
    archive: 'archive',
    languages: 'languages',
    search: 'search',
    disabled: 'disabled',
    embrace: 'Embrace your dark power!',
    join: 'Join dark side',
    themeChange: 'light/dark',
    people: 'People',
    itSeems: 'It seems like there is nothing by that address',
    goHome: 'Go home'
  },
  cs: {
    navbar: 'domov',
    planets: 'Planety',
    archive: 'archiv',
    languages: 'jazyk',
    search: 'Hledat',
    disabled: 'Nedostupné',
    embrace: 'Přijmi svou temnou sílu!',
    join: 'Přidejte se k temné straně',
    themeChange: 'světlo/tma',
    people: 'lidé',
    itSeems: 'It seems like there is nothing by that address',
    goHome: 'Jdi domů'
  },
  es: {
    navbar: 'Inicio',
    planets: 'Planetas',
    archive: 'archivo',
    languages: 'idiomas',
    search: 'buscar',
    disabled: 'No disponible',
    embrace: '¡Abraza tu poder oscuro!',
    join: 'Únete al lado oscuro',
    themeChange: 'claro/oscuro',
    people: 'Personas',
    itSeems: 'Parece que no hay nada en esta dirección',
    goHome: 'Inicio'
  },
  de: {
    navbar: 'Startseite',
    planets: 'Planeten',
    archive: 'Archiv',
    languages: 'Sprachen',
    search: 'Suche',
    disabled: 'Nicht verfügbar',
    embrace: 'Umfasse deine dunkle Macht!',
    join: 'Tritt der dunklen Seite bei',
    themeChange: 'hell/dunkel',
    people: 'Menschen',
    itSeems: 'Es scheint, dass es unter dieser Adresse nichts gibt',
    goHome: 'Startseite'
  },
  fr: {
    navbar: 'Accueil',
    planets: 'Planètes',
    archive: 'archive',
    languages: 'langues',
    search: 'recherche',
    disabled: 'Indisponible',
    embrace: 'Embrasse ton pouvoir sombre !',
    join: 'Rejoindre le côté obscur',
    themeChange: 'clair/sombre',
    people: 'Personnes',
    itSeems: "Il semble qu'il n'y ait rien à cette adresse",
    goHome: 'Accueil'
  },
  it: {
    navbar: 'Home',
    planets: 'Pianeti',
    archive: 'archivio',
    languages: 'lingue',
    search: 'cerca',
    disabled: 'Non disponibile',
    embrace: 'Abbraccia il tuo potere oscuro!',
    join: 'Unisciti al lato oscuro',
    themeChange: 'chiaro/scuro',
    people: 'Persone',
    itSeems: 'Sembra che non ci sia nulla a questo indirizzo',
    goHome: 'Home'
  },
};

export default languages;
